### ISSUE TITLE
parse_mode Markdown and HTML

### ISSUE THREAD

**Issue by axi92** [Dragory/telegram-bot-api#2]
How can i use Markdown at sendMessage?
https://core.telegram.org/bots/api#sendmessage

I was not able to use it.

**Comment by sIiiS** [comment]
I have this problem too
when I use `Markdown` then message not load and when I use `HTML` then nothing happen!

**Comment by Dragory** [comment]
Unfortunately, I haven't updated this package in a long time and it's no longer actively maintained. I recommend looking at some alternatives, such as https://github.com/yagop/node-telegram-bot-api.
